# Generated by Django 3.1.6 on 2021-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_slider_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
