# Generated by Django 3.1.6 on 2021-02-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210217_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='photo',
        ),
    ]
