# Generated by Django 3.1.6 on 2021-02-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_slider_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='number',
        ),
        migrations.AddField(
            model_name='slider',
            name='link_number',
            field=models.PositiveIntegerField(default='5', max_length=3),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_number',
            field=models.PositiveIntegerField(default='5', max_length=3),
        ),
    ]
