# Generated by Django 3.1.6 on 2021-02-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210217_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='link_number',
            field=models.PositiveIntegerField(default='5'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_number',
            field=models.PositiveIntegerField(default='5'),
        ),
    ]
