# Generated by Django 3.1.6 on 2021-02-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='myid',
            field=models.CharField(default=145, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
