# Generated by Django 3.1.6 on 2021-02-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210206_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['publish_date']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='myid',
        ),
    ]
