# Generated by Django 3.1.6 on 2021-02-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210207_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='items',
        ),
        migrations.RemoveField(
            model_name='packitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='packitem',
            name='pack',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
        migrations.DeleteModel(
            name='PackItem',
        ),
    ]
