# Generated by Django 3.1.6 on 2021-02-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product2',
            new_name='Wood',
        ),
    ]
