# Generated by Django 3.1.6 on 2021-02-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210215_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='photo5',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
