# Generated by Django 3.1.6 on 2021-02-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210215_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='details',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='child',
            name='code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
